version: '3.9'

services:
  
  rabbitmq-query-bus:
    image: rabbitmq:3-management
    container_name: trybe-git-score-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - trybe-network

  mongo:
    image: mongo
    container_name: trybe-git-score-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: desenvolvedor
      MONGO_INITDB_ROOT_PASSWORD: zikaMottu7000
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
    networks:
      - trybe-network
      
  influxdb:
    image: influxdb:latest
    container_name: trybe-git-score-influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=desenvolvedor
      - INFLUXDB_ADMIN_PASSWORD=zikaMottu7000
    networks:
      - trybe-network
  
volumes: 
    mongo-volume:
        driver: local 
    influxdb-storage:
        driver: local     

networks: 
  trybe-network:
    driver: bridge